workflows:
  my-workflow:
    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"
      - name: Discord notification
        script: | 
          set -ex
          
          # Publish the notification
          curl -H "Content-Type: multipart/form-data" \
          -F 'payload_json={"username" : "Hello 123", "content":"Demo 12313"}' \
          https://discord.com/api/webhooks/1080668695279435856/vcW5d2JsEqG5nETuUcoFMIknYixOjfz524b1mam7IL-RoqdgCPCUgmbI3N-s9JLxO7I8
